name: Backup to GitLab

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      # Create GitLab project with matching visibility (private or public)
      - name: Create GitLab project (if needed)
        run: |
          if [ "${{ github.event.repository.private }}" = "true" ]; then
            visibility="private"
          else
            visibility="public"
          fi
          curl --silent --fail --header "Authorization: Bearer ${{ secrets.GITLAB_TOKEN }}" \
            --data "{\"name\":\"${{ github.event.repository.name }}\",\"visibility\":\"$visibility\"}" \
            "https://gitlab.com/api/v4/projects" || echo "Project may already exist."
      
      # Clone the repository as a mirror
      - name: Clone repository as mirror
        run: |
          git clone --mirror https://github.com/${{ github.repository }}.git repo.git
      
      # Push the mirror to the corresponding GitLab project
      - name: Mirror push to GitLab
        run: |
          cd repo.git
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/${{ secrets.GITLAB_USERNAME }}/${{ github.event.repository.name }}.git
          git push --mirror gitlab
